export const POST_VALIDATION = Object.freeze({
  TITLE_MIN_LENGTH: 3,
  TITLE_MAX_LENGTH: 100,
  CONTENT_MIN_LENGTH: 0,
})

export const POST_TITLE_MIN_LENGTH = POST_VALIDATION.TITLE_MIN_LENGTH
export const POST_TITLE_MAX_LENGTH = POST_VALIDATION.TITLE_MAX_LENGTH
export const POST_CONTENT_MIN_LENGTH = POST_VALIDATION.CONTENT_MIN_LENGTH
