/** Regenerate with: bun packages/ui/scripts/artwork.ts */
import { deflateSync } from "node:zlib";
import { writeFileSync } from "node:fs";
import { cloudColor, contourColor, contourDensity } from "../src/lib/dither";
import { BAYER4 } from "../src/lib/pixel";

function crc32(bytes: Buffer) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++)
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Buffer) {
  const label = Buffer.from(type);
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([label, data])));
  return Buffer.concat([length, label, data, crc]);
}

function png(
  sample: (u: number, v: number, threshold: number) => number[],
  width = 960,
  height = 600,
) {
  const raw = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const rgba = sample(
        (x + 0.5) / width,
        (y + 0.5) / height,
        BAYER4[y & 3]![x & 3]!,
      );
      const offset = y * (1 + width * 4) + 1 + x * 4;
      for (let c = 0; c < 4; c++) raw[offset + c] = Math.round(rgba[c]!);
    }
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header[8] = 8;
  header[9] = 6;
  const bytes = Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk("IHDR", header),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
  return `data:image/png;base64,${bytes.toString("base64")}`;
}

const contours = png((u, v, threshold) => [
  ...contourColor(u, v, threshold),
  255,
]);
const clouds = png((u, v, threshold) => [...cloudColor(u, v, threshold), 255]);
const masks = Object.fromEntries(
  ["up", "down", "left", "right"].map((direction) => [
    direction,
    png(
      (u, v, threshold) => {
        const fade =
          direction === "up"
            ? v
            : direction === "down"
              ? 1 - v
              : direction === "left"
                ? u
                : 1 - u;
        const density =
          direction === "up"
            ? contourDensity(1 - u, 1 - v)
            : direction === "left"
              ? contourDensity(v, 1 - u)
              : direction === "right"
                ? contourDensity(1 - v, u)
                : contourDensity(u, v);
        const alpha =
          (density > threshold ? 0.75 + 0.25 * density : 0.035) *
          Math.sqrt(fade);
        return [0, 0, 0, (Math.round(alpha * 31) / 31) * 255];
      },
      320,
      200,
    ),
  ]),
);
writeFileSync(
  new URL("../src/lib/artwork.ts", import.meta.url),
  `// Generated by scripts/artwork.ts. Do not edit by hand.\nexport const contourArtwork = ${JSON.stringify(contours)};\nexport const cloudArtwork = ${JSON.stringify(clouds)};\nexport const contourMasks = ${JSON.stringify(masks)} as const;\n`,
);
